import "./globals.css";
import { AuthProvider } from '@/context/AuthContext';
import Script from 'next/script';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="min-h-screen bg-gray-900 text-gray-100">
            {children}
          </div>
          
          <Script 
            src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"
            strategy="lazyOnload"
          />
          <df-messenger
             project-id={process.env.NEXT_PUBLIC_PROJECT_ID}
             agent-id={process.env.NEXT_PUBLIC_AGENT_ID}
             language-code="en"
             chat-title="Emergency Assistant"
            style={{ 
              width: '100%',
              maxWidth: '400px',
              height: '500px',
              position: 'fixed',
              bottom: '20px',
              right: '20px'
            }}
          ></df-messenger>
        </AuthProvider>
      </body>
    </html>
  );
}
