import "./globals.css";
import { AuthProvider } from '@/context/AuthContext';
import ChatInterface from '@/components/ChatInterface';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="min-h-screen bg-gray-900 text-gray-100">
            {children}
            <ChatInterface defaultExpanded={true} />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
